spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:postgresql:mediatheque-postgresql
    username: postgres
    password: postgres
  
  jackson:
    serialization:
      fail-on-empty-beans: false
      
